### ISSUE TITLE
Try to run Ball detcetion mode and got this error: `overlap_filter_strategy`

### ISSUE THREAD

**Issue by MeharRamzan** [roboflow/sports#24]
![image](https://github.com/user-attachments/assets/280c54c6-f094-4297-a80e-e304f955196c)

**Comment by pplaatje** [comment]
@MeharRamzan you created and closed this issue, however I'm running into this as well. What did you do to fix it?

**Comment by cvillela** [comment]
Same question here @MeharRamzan

**Comment by cvillela** [comment]
@pplaatje don't know if this is useful, but I changed the overlap_filter_strategy flag with overlap_filter, as per the docs.

```
slicer = sv.InferenceSlicer(
        callback=callback,
        overlap_filter=sv.OverlapFilter.NONE,
        slice_wh=(640, 640),
    )
```

https://supervision.roboflow.com/0.25.0/detection/tools/inference_slicer/

@SkalskiP maybe this is useful
