### ISSUE TITLE
Code / Documentation 

### ISSUE THREAD

**Issue by sarthakg2002** [roboflow/sports#4]
Where can i find the code or the documentation to achieve the same results as the demo video provided. I couldn't find the main file where all the classes and helper function were called.

**Comment by chumpblocckami** [comment]
Please add the code for reproducing the demo, thanks

**Comment by SkalskiP** [comment]
Hi @sarthakg2002 and @chumpblocckami, most of the code was stored in a separate repository. It was moved here yesterday. I'm still working on documenting it, but you can find it [here](https://github.com/roboflow/sports/tree/main/examples/soccer).

**Comment by chumpblocckami** [comment]
hi @SkalskiP, thanks a lot for the update! :)
