### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 3227: character maps to <undefined>

### ISSUE THREAD

**Issue by Joe-KI333** [roboflow/sports#9]
![image](https://github.com/user-attachments/assets/c825464d-8951-472f-9e59-a3e4ae704fe7)

**Comment by dsaha21** [comment]
Hi @Joe-KI333 , 

@SkalskiP this was the error that I was talking about. 

@Joe-KI333 till then you can follow https://github.com/roboflow/sports/issues/7 

Thanks

**Comment by SkalskiP** [comment]
Hi @Joe-KI333 and @dsaha21 👋🏻, could you try once again? I specified the text encoding that should be used.

**Comment by Joe-KI333** [comment]
Thank you 😇

**Comment by SkalskiP** [comment]
Does it work? ;)

**Comment by SkalskiP** [comment]
In that case, I'm closing the issue. Feel free to reopen it if you'll face more problems.

**Comment by Joe-KI333** [comment]
@SkalskiP Yes Sir You can now it is working thank you
